In [17]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [18]:
import numpy as np

arr = np.arange(6)
print("Data type of array:", arr.dtype)


Data type of array: int64


In [19]:
#2Check if the data type of a given NumPy array 'arr' is float64.

In [20]:
arr = np.array([1.5, 2.6, 3.7])
if arr.dtype == np.float64:
    print("The data type is float64.")
else:
    print("The data type is not float64.")


The data type is float64.


In [21]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [22]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [23]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type

In [24]:
arr_float = arr.astype(np.float32)
print(arr_float)


[1. 3. 5.]


C:\Users\HP\AppData\Local\Temp\ipykernel_3848\1919599306.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr_float = arr.astype(np.float32)


In [25]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [26]:
arr_float32 = arr.astype(np.float32)
print(arr_float32)


[1. 3. 5.]


C:\Users\HP\AppData\Local\Temp\ipykernel_3848\3492615239.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  arr_float32 = arr.astype(np.float32)


In [27]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [33]:
import numpy as np
def array_attributes(arr):
        return arr.shape, arr.size, arr.dtype

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
x=array_attributes(arr)
print("Attributes (Shape, Size, Dtype):",x)                                                                                                                             

Array: [1 2 3 4 5]
Attributes (Shape, Size, Dtype): ((5,), 5, dtype('int64'))


In [29]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [34]:
def array_dimension(arr):
        return arr.ndim

arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Array:\n", arr)
print("Dimension:", array_dimension(arr))

Array:
 [[1 2]
 [3 4]
 [5 6]]
Dimension: 2


In [21]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and total size in bytes.

In [35]:
def item_size_info(arr):
        return arr.itemsize, arr.nbytes

arr = np.array([1.0, 2.0, 3.0])
print("Array:", arr)
print("Item size (bytes):", item_size_info(arr)[0])
print("Total size (bytes):", item_size_info(arr)[1])

Array: [1. 2. 3.]
Item size (bytes): 8
Total size (bytes): 24


In [36]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [38]:
def array_strides(arr):
        return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Strides:", array_strides(arr))

Array:
 [[1 2 3]
 [4 5 6]]
Strides: (24, 8)


In [39]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [40]:
def shape_stride_relationship(arr):
        return arr.shape, arr.strides

arr = np.array([[1, 2], [3, 4]])
print("Array:\n", arr)
print("Shape:", shape_stride_relationship(arr)[0])
print("Strides:", shape_stride_relationship(arr)[1])

Array:
 [[1 2]
 [3 4]]
Shape: (2, 2)
Strides: (16, 8)


In [41]:
#11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.

In [42]:
def create_zeros_array(n):
        return np.zeros(n)

print("Zeros array:", create_zeros_array(5))


Zeros array: [0. 0. 0. 0. 0.]


In [43]:
#12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D array filled with ones of size rows x cols.

In [44]:
def create_ones_matrix(rows, cols):
        return np.ones((rows, cols))

print("Ones matrix:\n", create_ones_matrix(3, 4))



Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [45]:
#13. Write a function generate_range_array that creates a NumPy array with a range from start to stop with a step size.

In [46]:
def generate_range_array(start, stop, step):
        return np.arange(start, stop, step)

print("Range array:", generate_range_array(1, 10, 2))



Range array: [1 3 5 7 9]


In [47]:
#14. Design a function generate_linear_space that generates num equally spaced values between start and stop.

In [48]:
def generate_linear_space(start, stop, num):
        return np.linspace(start, stop, num)

print("Linear space:", generate_linear_space(0, 1, 5))



Linear space: [0.   0.25 0.5  0.75 1.  ]


In [50]:
#15. Create a function create_identity_matrix that generates a square identity matrix of size n x n.python Copy code


def create_identity_matrix(n):
        return np.eye(n)


print("Identity matrix:\n", create_identity_matrix(3))


Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
#16. Write a function to convert a Python list into a NumPy array.

In [52]:
def list_to_array(py_list):
        return np.array(py_list)

py_list = [1, 2, 3, 4]

print("Converted array:", list_to_array(py_list))



Converted array: [1 2 3 4]


In [53]:
#17. Demonstrate the use of numpy.view to create a new array object with the same data.

In [54]:
def main_numpy_view():
    import numpy as np
    arr = np.array([1, 2, 3, 4])
    view_arr = arr.view()
    print("Original array:", arr)
    print("View array:", view_arr)
arr = np.array([1.5, 2.6, 3.7])
view_arr = arr.view()
print("Original array:", arr)
print("View array:", view_arr)


Original array: [1.5 2.6 3.7]
View array: [1.5 2.6 3.7]


In [55]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [57]:
def concatenate_arrays(arr1, arr2, axis=0):
        return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Concatenated array:", concatenate_arrays(arr1, arr2))


Concatenated array: [1 2 3 4 5 6]


In [58]:
#19. Concatenate two NumPy arrays with different shapes horizontally.

In [59]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
result = np.concatenate((arr1, arr2.T), axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


In [60]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [61]:
def main_vertical_stack_arrays():
    import numpy as np
    def vertical_stack_arrays(array_list):
        return np.vstack(array_list)

    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    print("Vertically stacked arrays:\n", vertical_stack_arrays([arr1, arr2]))
main_vertical_stack_arrays()

Vertically stacked arrays:
 [[1 2 3]
 [4 5 6]]


In [62]:
#21. Write a function to create an array of integers within a range (inclusive) with a step size.

In [63]:
def main_create_integer_range_array():
    import numpy as np
    def create_integer_range_array(start, stop, step):
        return np.arange(start, stop + 1, step)

    print("Integer range array:", create_integer_range_array(1, 10, 2))
main_create_integer_range_array()

Integer range array: [1 3 5 7 9]


In [64]:
#22. Generate an array of 10 equally spaced values between 0 and 1

In [65]:
def main_generate_equally_spaced_values():
    import numpy as np
    def generate_equally_spaced_values():
        return np.linspace(0, 1, 10)

    print("Equally spaced values:", generate_equally_spaced_values())
main_generate_equally_spaced_values()


Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [66]:
#23. Create an array of 5 logarithmically spaced values between 1 and 1000.

In [67]:
def main_generate_log_spaced_values():
    import numpy as np
    def generate_log_spaced_values():
        return np.logspace(0, 3, 5, base=10)

    print("Logarithmically spaced values:", generate_log_spaced_values())
main_generate_log_spaced_values()


Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [68]:
#24. Create a Pandas DataFrame with random integers.

In [69]:
def main_create_pandas_dataframe():
    import numpy as np
    import pandas as pd
    def create_dataframe():
        data = np.random.randint(1, 101, (5, 3))
        return pd.DataFrame(data, columns=["Column1", "Column2", "Column3"])

    df = create_dataframe()
    print("Random DataFrame:\n", df)
main_create_pandas_dataframe()


Random DataFrame:
    Column1  Column2  Column3
0       87       85       88
1       58       91       17
2       99       56       55
3       20       88       62
4       49       96       11


In [70]:
#25. Replace all negative values in a specific column of a Pandas DataFrame with zeros.

In [71]:
def main_replace_negative_values():
    import pandas as pd
    import numpy as np
    def replace_negative_values(df, column):
        df[column] = np.where(df[column] < 0, 0, df[column])
        return df

    # Example DataFrame
    data = {
        "A": [1, -2, 3],
        "B": [-4, 5, -6],
        "C": [7, -8, 9]
    }
    df = pd.DataFrame(data)
    print("Original DataFrame:\n", df)

    # Replace negative values in column 'B'
    df = replace_negative_values(df, "B")
    print("Updated DataFrame:\n", df)
main_replace_negative_values()


Original DataFrame:
    A  B  C
0  1 -4  7
1 -2  5 -8
2  3 -6  9
Updated DataFrame:
    A  B  C
0  1  0  7
1 -2  5 -8
2  3  0  9


In [72]:
#26. Access the 3rd element from the given NumPy array

In [75]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [79]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1][2])

6


In [82]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7]) 
for i in arr:
    if i>5:
        print(i)

8
10
7


In [83]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
x = arr[2:6:1]
print(x)

[3 4 5 6]


In [84]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_arr = arr_2d[0:2, 1:3]

print(sub_arr)


[[2 3]
 [5 6]]


In [87]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1],   # row 0, column 1
                    [1, 2],   # row 1, column 2
                    [2, 0]])  # row 2, column 0

result = arr_2d[indices[:, 0], indices[:, 1]]
print(result)

[2 6 7]


In [89]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_above_threshold(arr, threshold):
    
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 3, 8, 2, 7])
threshold = 4
filtered_arr = filter_above_threshold(arr, threshold)
print(filtered_arr)  

[5 8 7]


In [91]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_3d_elements(arr, x_indices, y_indices, z_indices):
    
    return arr[x_indices, y_indices, z_indices]

# Example usage
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x_indices = np.array([0, 1])
y_indices = np.array([1, 0])
z_indices = np.array([0, 1])
result = extract_3d_elements(arr_3d, x_indices, y_indices, z_indices)
print(result)  

[3 6]


In [93]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def filter_multiple_conditions(arr, cond1, cond2):
    
    return arr[(cond1) & (cond2)]

# Example usage
arr = np.array([1, 5, 3, 8, 2, 7])
result = filter_multiple_conditions(arr, arr > 3, arr % 2 == 1)
print(result)  

[5 7]


In [96]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_by_row_col_indices(arr, row_indices, col_indices):
    
    return arr[row_indices, col_indices]

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = extract_by_row_col_indices(arr_2d, row_indices, col_indices)
print(result)  

[2 6 7]


In [97]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

def add_scalar_broadcast(arr, scalar):
   
    return arr + scalar

# Example usage
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
result = add_scalar_broadcast(arr, 5)
print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [106]:
import numpy as np

def multiply_rows_broadcast(arr1, arr2):
    
    # Reshape arr1 to allow proper broadcasting
    return arr1.reshape(-1, 1) * arr2

# Example usage
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
result = multiply_rows_broadcast(arr1, arr2)
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [101]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

def add_to_rows_broadcast(arr1, arr2):
    return arr1 + arr2.T

# Example usage
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
result = add_to_rows_broadcast(arr1, arr2)
print(result)

[[ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [102]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

def add_arrays_broadcast(arr1, arr2):
    return arr1 + arr2

# Example usage
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([4, 5, 6])
result = add_arrays_broadcast(arr1, arr2)
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [104]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility
import numpy as np

def multiply_arrays_broadcast(arr1, arr2):
    
    try:
        return arr1 * arr2
    except ValueError:
        # Pad the smaller array or handle incompatibility
        # In this case, we'll use the minimum common shape
        min_rows = min(arr1.shape[0], arr2.shape[0])
        min_cols = min(arr1.shape[1], arr2.shape[1])
        return arr1[:min_rows, :min_cols] * arr2[:min_rows, :min_cols]

# Example usage
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 2],
                 [3, 4]])
result = multiply_arrays_broadcast(arr1, arr2)
print(result)

[[ 1  4]
 [12 20]]


In [108]:
#41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_mean = np.mean(arr, axis=0)
print(arr_mean)

[2.5 3.5 4.5]


In [110]:
#42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_max = np.max(arr, axis=1)
print(arr_max)

[3 6]


In [111]:
#43. For the given array, find indices of maximum value in each column.
arr_max_indices = np.argmax(arr, axis=0)
print(arr_max_indices)

[1 1 1]


In [113]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(row):
    return np.cumsum(row)

arr_moving_sum = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(arr_moving_sum)

[[ 1  3  6]
 [ 4  9 15]]


In [114]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr_even = np.all(arr % 2 == 0, axis=0)
print(arr_even)

[False False False]


In [115]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = original_array.reshape(2, 3)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


In [116]:
#47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(input_matrix):
    return input_matrix.flatten()

input_matrix = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [117]:
#48. Write a function that concatenates two given arrays along a specified axis.

def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (vertically)
result_vertical = concatenate_arrays(array1, array2, axis=0)
print(result_vertical)

# Concatenate along axis 1 (horizontally)
result_horizontal = concatenate_arrays(array1, array2, axis=1)
print(result_horizontal)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [118]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(original_array, axis):
    return np.split(original_array, indices_or_sections=original_array.shape[axis], axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Split along axis 0 (rows)
sub_arrays_rows = split_array(original_array, axis=0)
print(sub_arrays_rows)

# Split along axis 1 (columns)
sub_arrays_cols = split_array(original_array, axis=1)
print(sub_arrays_cols)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [119]:
#50.Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements
    new_array = np.insert(original_array, indices_to_insert, values_to_insert, axis=0)
    
    # Delete elements
    new_array = np.delete(new_array, indices_to_delete, axis=0)
    
    return new_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

modified_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(modified_array)

[ 1 10  4 11  5]


In [190]:
#51. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 10. Perform element-wise addition between 'arr1' and 'arr2'.

# Create 'arr1' with random integers
arr1 = np.random.randint(0, 20, size=(3, 4))

# Create 'arr2' with integers from 1 to 12 (to match the shape of 'arr1')
arr2 = np.arange(1, 13).reshape(3, 4)

# Perform element-wise addition
result = arr1 + arr2
print(result)

[[11 21 21 21]
 [14 23 15 13]
 [17 25 17 23]]


In [121]:
#52.Generate a NumPy array 'arr1' with sequential integers from 10 to 1 and another array 'arr2' with integers from 1 to 10. Subtract 'arr2' from 'arr1' element-wise.



# Create 'arr1' with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Create 'arr2' with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2
print(result)

[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [122]:
#53. Create a NumPy array 'arr1' with random integers and another array 'arr2' with integers from 1 to 5. Perform element-wise multiplication between 'arr1' and 'arr2'.

# Create 'arr1' with random integers
arr1 = np.random.randint(0, 10, size=(3, 4))

# Create 'arr2' with integers from 1 to 5
arr2 = np.arange(1, 6).reshape(1, 5)

# Perform element-wise multiplication
result = arr1 * arr2[:, :arr1.shape[1]]
print(result)

[[ 3  6  6 16]
 [ 8  0 15 24]
 [ 0  2 24  4]]


In [123]:
#54. Generate a NumPy array 'arr1' with even integers from 2 to 10 and another array 'arr2' with integers from 1 to 5. Perform element-wise division of 'arr1' by 'arr2'.

# Create 'arr1' with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create 'arr2' with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2
print(result)

[2. 2. 2. 2. 2.]


In [124]:
#55. Create a NumPy array 'arr1' with integers from 1 to 5 and another array 'arr2' with the same numbers reversed. Calculate the exponentiation of 'arr1' raised to the power of 'arr2' element-wise.

# Create 'arr1' with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create 'arr2' with the same numbers reversed
arr2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise exponentiation
result = np.power(arr1, arr2)
print(result)

[ 1 16 27 16  5]


In [125]:
#56. Create a NumPy array 'arr1' with integers from 1 to 5 and another array 'arr2' with the same numbers reversed. Calculate the exponentiation of 'arr1' raised to the power of 'arr2' element-wise.

# Create 'arr1' with integers from 1 to 5
arr1 = np.arange(1, 6)

# Create 'arr2' with the same numbers reversed
arr2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise exponentiation
result = np.power(arr1, arr2)
print(result)

[ 1 16 27 16  5]


In [189]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

import numpy as np

def extract_uppercase(arr):
    return np.array([s for s in arr if s.isupper()])

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)

['GPT']


In [129]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring(arr, 'apple', 'kiwi')
print(new_arr)

['kiwi' 'banana' 'grape' 'pinekiwi']


In [130]:
#59.Write a function that concatenates strings in a NumPy array element-wise.
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.core.defchararray.add(arr1, arr2)

# Example usage
arr1 = np.array(['Hello', 'World'])
arr2 = np.array([' Open', ' AI'])
result = concatenate_strings(arr1, arr2)
print(result)

['Hello Open' 'World AI']


C:\Users\HP\AppData\Local\Temp\ipykernel_3848\136536336.py:5: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.defchararray.
  return np.core.defchararray.add(arr1, arr2)


In [132]:
#60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def find_longest_string(arr):
   
    return np.max(np.char.str_len(arr))

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = find_longest_string(arr)
print(longest_length)

9


In [142]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)



Mean: 492.79
Median: 525.5
Variance: 90261.3659
Standard Deviation: 300.43529403184306


In [143]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, size=50)

# Find the 25th and 75th percentiles
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


25th Percentile: 15.0
75th Percentile: 65.75


In [144]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

import numpy as np

# Create two arrays representing two sets of variables
arr1 = np.random.normal(0, 1, size=(10,))
arr2 = np.random.normal(0, 1, size=(10,))

# Compute the correlation coefficient
correlation_coeff = np.corrcoef(arr1, arr2)[0, 1]

print("Correlation Coefficient:", correlation_coeff)


Correlation Coefficient: 0.22153469663214512


In [145]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
import numpy as np

# Create two matrices
matrix1 = np.random.randint(1, 11, size=(3, 4))
matrix2 = np.random.randint(1, 11, size=(4, 5))

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result:\n", result)



Matrix 1:
 [[ 5  8  3 10]
 [ 9  3  4  5]
 [10  4  4  1]]
Matrix 2:
 [[ 2  4  2  9  4]
 [ 7 10  2  1  2]
 [ 1  8  1  2  2]
 [ 9  3 10  6  5]]
Result:
 [[159 154 129 119  92]
 [ 88 113  78 122  75]
 [ 61 115  42 108  61]]


In [146]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
import numpy as np

# Create an array of 50 integers between 10 and 1000
dataset = np.random.randint(10, 1001, size=50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(dataset, 10)
median = np.percentile(dataset, 50)
percentile_90 = np.percentile(dataset, 90)

# Calculate the first and third quartiles
q1 = np.percentile(dataset, 25)
q3 = np.percentile(dataset, 75)

print("10th Percentile:", percentile_10)
print("Median:", median)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", q1)
print("Third Quartile (Q3):", q3)



10th Percentile: 172.10000000000002
Median: 463.0
90th Percentile: 858.0
First Quartile (Q1): 322.25
Third Quartile (Q3): 716.0


In [147]:
#66. Create a NumPy array of integers and find the index of a specific element.
import numpy as np

# Create a NumPy array of integers
arr = np.array([5, 10, 15, 20, 25, 30])

# Find the index of a specific element
target_element = 20
index = np.where(arr == target_element)[0][0]

print("Index of", target_element, "is:", index)



Index of 20 is: 3


In [148]:
#67. Generate a random NumPy array and sort it in ascending order
import numpy as np

# Generate a random NumPy array
arr = np.random.randint(1, 101, size=15)

# Sort the array in ascending order
sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)

Original Array: [ 3 97 35 52 80 96  9 73 57 74 56 21 29 75 39]
Sorted Array: [ 3  9 21 29 35 39 52 56 57 73 74 75 80 96 97]


In [149]:
#68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements > 20
filtered_arr = arr[arr > 20]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)

Original Array: [12 25  6 42  8 30]
Filtered Array: [25 42 30]


In [150]:
#69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])
import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)

Original Array: [ 1  5  8 12 15]
Filtered Array: [12 15]


In [152]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original Array:", arr)
print("Filtered Array:", filtered_arr)

Original Array: [10 20 30 40 50]
Filtered Array: [20 30 40]


In [153]:
#71.For the given NumPy array, check its byte order using the 'dtype' attribute byteorder.

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

print("Byte Order:", byte_order)

Byte Order: =


In [154]:
#72. For the given NumPy array, perform byte swapping in place using 'byteswap()'.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [182]:
#73. For the given NumPy array, swap its bytes order without modifying the original array using 'newbyteorder()'.

arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.view(arr.dtype.newbyteorder())

In [184]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using 'newbyteorder()'.
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.view(arr.dtype.newbyteorder())


In [185]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using 'dtype' attribute 'byteorder'.
import sys

arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder != sys.byteorder:
    arr.byteswap(inplace=True)


In [160]:
#76. Create a NumPy array 'arr1' with values from 1 to 10. Create a copy of 'arr1' named 'copy_arr' and modify an element in 'copy_arr'. Check if modifying 'copy_arr' affects 'arr1'.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
#Modifying 'copy_arr' does not affect 'arr1'


In [161]:
#77. Create a 2D NumPy array 'matrix' of shape (3, 3) with random integers. Extract a slice 'view_slice' from the matrix. Modify an element in 'view_slice' and observe if it changes the original 'matrix'.
matrix = np.random.randint(0, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100
#Modifying 'view

In [165]:
#78. Create a NumPy array 'array_a' of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 'view_b' from 'array_a' and broadcast the addition of 5 to 'view_b'. Check if it alters the original 'array_a'.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:3, :]
view_b += 5
print("Modifying 'view_b' does change the original 'array_a'. ")

Modifying 'view_b' does change the original 'array_a'. 


In [166]:
#79. Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8. Create a reshaped view 'reshaped_view' of shape (4, 2) from 'orig_array'. Modify an element in 'reshaped_view' and check if it reflects changes in the original 'orig_array'.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.T
reshaped_view[0, 0] = 100
print("Modifying 'reshaped_view' does change the original 'orig_array'")

Modifying 'reshaped_view' does change the original 'orig_array'


In [167]:
#80. Create a NumPy array 'data' of shape (3, 4) with random integers. Extract a copy 'data_copy' of elements greater than 5. Modify an element in 'data_copy' and verify if it affects the original 'data'.
data = np.random.randint(0, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100
print("Modifying 'data_copy' does not affect the original 'data'")

Modifying 'data_copy' does not affect the original 'data'


In [171]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
D = A - B
print(C)
print(D)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [172]:
#82. Generate two matrices 'C' (3x2) and 'D' (2x4) and perform matrix multiplication.
C = np.random.randint(0, 10, size=(3, 2))
D = np.random.randint(0, 10, size=(2, 4))
E = np.matmul(C, D)
print(E)

[[87 76 51 48]
 [72 64 24 48]
 [74 64 54 36]]


In [174]:
#83. Create a matrix 'E' and find its transpose.
E = np.random.randint(0, 10, size=(3, 3))
E_transpose = E.T
print(E_transpose)

[[2 1 4]
 [5 7 0]
 [6 4 1]]


In [176]:
#84. Generate a square matrix 'F' and compute its determinant.
F = np.random.randint(0, 10, size=(3, 3))
det_F = np.linalg.det(F)
print(det_F)

-30.000000000000014


In [178]:
#85. Create a square matrix 'G' and find its inverse.
G = np.random.randint(0, 10, size=(3, 3))
G_inverse = np.linalg.inv(G)
print(G_inverse)

[[ 0.48 -0.32  0.2 ]
 [-0.3   0.2  -0.  ]
 [-0.16  0.44 -0.4 ]]
